import {
  FlowCurrents,
  //GravityStorm,
  GeoPulse,
  WaveEther,
  //VortexBloom,
  //CrystallineDrift,
  AmbientMesh,
  //EmberCascade,
  //CliffordAttractor,
  HarmonicLattice,
  LissajousWeave,
  PhyllotaxisDream,
  //Spirograph,
  //DifferentialGrowth,
  //DoublePendulum,
  FractalNoiseTerrain,
  MoireLattice,
  NeuralWeave,
  OrbitalResonance,
  //ReactionDiffusion,
  RecursiveSubdivision,
  TideHarmonics,
  VoronoiMosaic,
  PlasmaField,
  NebulaVeil,
  PrismaticWave,
  PhotonBurst,
  FibonacciVortex,
  HexRipple,
  RecursiveTunnel,
  flowCurrentsSchema,
  flowCurrentsDefaults,
  //gravityStormSchema,
  //gravityStormDefaults,
  geoPulseSchema,
  geoPulseDefaults,
  waveEtherSchema,
  waveEtherDefaults,
  //vortexBloomSchema,
  //vortexBloomDefaults,
  //crystallineDriftSchema,
  //crystallineDriftDefaults,
  ambientMeshSchema,
  ambientMeshDefaults,
  //emberCascadeSchema,
  //emberCascadeDefaults,
  //cliffordAttractorSchema,
  //cliffordAttractorDefaults,
  harmonicLatticeSchema,
  harmonicLatticeDefaults,
  lissajousWeaveSchema,
  lissajousWeaveDefaults,
  phyllotaxisDreamSchema,
  phyllotaxisDreamDefaults,
  //spirographSchema,
  //spirographDefaults,
  //differentialGrowthSchema,
  //differentialGrowthDefaults,
  //doublePendulumSchema,
  //doublePendulumDefaults,
  fractalNoiseTerrainSchema,
  fractalNoiseTerrainDefaults,
  moireLatticeSchema,
  moireLatticeDefaults,
  neuralWeaveSchema,
  neuralWeaveDefaults,
  orbitalResonanceSchema,
  orbitalResonanceDefaults,
  //reactionDiffusionSchema,
  //reactionDiffusionDefaults,
  recursiveSubdivisionSchema,
  recursiveSubdivisionDefaults,
  tideHarmonicsSchema,
  tideHarmonicsDefaults,
  voronoiMosaicSchema,
  voronoiMosaicDefaults,
  plasmaFieldSchema,
  plasmaFieldDefaults,
  nebulaVeilSchema,
  nebulaVeilDefaults,
  prismaticWaveSchema,
  prismaticWaveDefaults,
  photonBurstSchema,
  photonBurstDefaults,
  fibonacciVortexSchema,
  fibonacciVortexDefaults,
  hexRippleSchema,
  hexRippleDefaults,
  recursiveTunnelSchema,
  recursiveTunnelDefaults,
} from "alg-art-backgrounds";
import type { BackgroundEntry, AnyParams } from "./types";

export const BACKGROUNDS: BackgroundEntry[] = [
  {
    id: "flow-currents",
    label: "Flow Currents",
    schema: flowCurrentsSchema,
    defaults: flowCurrentsDefaults as AnyParams,
    Component: FlowCurrents,
    description: "Particles trace Perlin noise vector fields.",
  },
  /*{
    id: "gravity-storm",
    label: "Gravity Storm",
    schema: gravityStormSchema,
    defaults: gravityStormDefaults as AnyParams,
    Component: GravityStorm,
    description: "Orbital particle choreography around moving attractors.",
  },*/
  {
    id: "geo-pulse",
    label: "Geo Pulse",
    schema: geoPulseSchema,
    defaults: geoPulseDefaults as AnyParams,
    Component: GeoPulse,
    description: "Nested rotating polygons at prime-ratio angular velocities.",
  },
  {
    id: "wave-ether",
    label: "Wave Ether",
    schema: waveEtherSchema,
    defaults: waveEtherDefaults as AnyParams,
    Component: WaveEther,
    description: "Multi-source interference waves across a pixel grid.",
  },
  /*{
    id: "vortex-bloom",
    label: "Vortex Bloom",
    schema: vortexBloomSchema,
    defaults: vortexBloomDefaults as AnyParams,
    Component: VortexBloom,
    description: "Particles spiral under competing vortex attractors.",
  },*/
  /*{
    id: "crystalline-drift",
    label: "Crystalline Drift",
    schema: crystallineDriftSchema,
    defaults: crystallineDriftDefaults as AnyParams,
    Component: CrystallineDrift,
    description: "Recursive branching arms form snowflake-like crystals.",
  },*/
  {
    id: "ambient-mesh",
    label: "Ambient Mesh",
    schema: ambientMeshSchema,
    defaults: ambientMeshDefaults as AnyParams,
    Component: AmbientMesh,
    description:
      "Nodes drift through noise fields forming dynamic connections.",
  },
  /*{
    id: "ember-cascade",
    label: "Ember Cascade",
    schema: emberCascadeSchema,
    defaults: emberCascadeDefaults as unknown as AnyParams,
    Component: EmberCascade,
    description: "Thermal particles rise with turbulent motion and glow.",
  },*/
  /*{
    id: "clifford-attractor",
    label: "Clifford Attractor",
    schema: cliffordAttractorSchema,
    defaults: cliffordAttractorDefaults as unknown as AnyParams,
    Component: CliffordAttractor,
    description: "Strange attractor density map revealing fractal chaos.",
  },*/
  {
    id: "harmonic-lattice",
    label: "Harmonic Lattice",
    schema: harmonicLatticeSchema,
    defaults: harmonicLatticeDefaults as unknown as AnyParams,
    Component: HarmonicLattice,
    description: "Standing wave interference patterns with nodal lines.",
  },
  {
    id: "lissajous-weave",
    label: "Lissajous Weave",
    schema: lissajousWeaveSchema,
    defaults: lissajousWeaveDefaults as unknown as AnyParams,
    Component: LissajousWeave,
    description: "Harmonic phase tapestry with multiple frequency ratios.",
  },
  {
    id: "phyllotaxis-dream",
    label: "Phyllotaxis Dream",
    schema: phyllotaxisDreamSchema,
    defaults: phyllotaxisDreamDefaults as unknown as AnyParams,
    Component: PhyllotaxisDream,
    description: "Golden angle spiral growth pattern.",
  },
  /*{
    id: "spirograph",
    label: "Spirograph",
    schema: spirographSchema,
    defaults: spirographDefaults as unknown as AnyParams,
    Component: Spirograph,
    description: "Hypotrochoid curves from rolling circles.",
  },*/
  /*{
    id: "differential-growth",
    label: "Differential Growth",
    schema: differentialGrowthSchema,
    defaults: differentialGrowthDefaults as unknown as AnyParams,
    Component: DifferentialGrowth,
    description: "Organic growth with spring forces and repulsion.",
  },*/
  /*{
    id: "double-pendulum",
    label: "Double Pendulum",
    schema: doublePendulumSchema,
    defaults: doublePendulumDefaults as unknown as AnyParams,
    Component: DoublePendulum,
    description: "Chaotic dynamics with RK4 integration.",
  },*/
  {
    id: "fractal-noise-terrain",
    label: "Fractal Noise Terrain",
    schema: fractalNoiseTerrainSchema,
    defaults: fractalNoiseTerrainDefaults as unknown as AnyParams,
    Component: FractalNoiseTerrain,
    description: "Layered octaves creating procedural landscapes.",
  },
  {
    id: "moire-lattice",
    label: "Moire Lattice",
    schema: moireLatticeSchema,
    defaults: moireLatticeDefaults as unknown as AnyParams,
    Component: MoireLattice,
    description: "Rotating line grids creating interference patterns.",
  },
  {
    id: "neural-weave",
    label: "Neural Weave",
    schema: neuralWeaveSchema,
    defaults: neuralWeaveDefaults as unknown as AnyParams,
    Component: NeuralWeave,
    description: "Network nodes with traveling signal pulses.",
  },
  {
    id: "orbital-resonance",
    label: "Orbital Resonance",
    schema: orbitalResonanceSchema,
    defaults: orbitalResonanceDefaults as unknown as AnyParams,
    Component: OrbitalResonance,
    description: "Bodies orbit at resonant period ratios.",
  },
  /*{
    id: "reaction-diffusion",
    label: "Reaction Diffusion",
    schema: reactionDiffusionSchema,
    defaults: reactionDiffusionDefaults as unknown as AnyParams,
    Component: ReactionDiffusion,
    description: "Gray-Scott model pattern formation.",
  },*/
  {
    id: "recursive-subdivision",
    label: "Recursive Subdivision",
    schema: recursiveSubdivisionSchema,
    defaults: recursiveSubdivisionDefaults as unknown as AnyParams,
    Component: RecursiveSubdivision,
    description: "Binary space partitioning (Mondrian-like).",
  },
  {
    id: "tide-harmonics",
    label: "Tide Harmonics",
    schema: tideHarmonicsSchema,
    defaults: tideHarmonicsDefaults as unknown as AnyParams,
    Component: TideHarmonics,
    description: "Wave interference along horizontal lines.",
  },
  {
    id: "voronoi-mosaic",
    label: "Voronoi Mosaic",
    schema: voronoiMosaicSchema,
    defaults: voronoiMosaicDefaults as unknown as AnyParams,
    Component: VoronoiMosaic,
    description: "Dynamic Voronoi tessellation.",
  },
  {
    id: "plasma-field",
    label: "Plasma Field",
    schema: plasmaFieldSchema,
    defaults: plasmaFieldDefaults as unknown as AnyParams,
    Component: PlasmaField,
    description: "Domain-warped fBm plasma at pixel resolution via WebGL2.",
  },
  {
    id: "nebula-veil",
    label: "Nebula Veil",
    schema: nebulaVeilSchema,
    defaults: nebulaVeilDefaults as unknown as AnyParams,
    Component: NebulaVeil,
    description: "Three noise layers interfering into a volumetric nebula curtain.",
  },
  {
    id: "prismatic-wave",
    label: "Prismatic Wave",
    schema: prismaticWaveSchema,
    defaults: prismaticWaveDefaults as unknown as AnyParams,
    Component: PrismaticWave,
    description: "Wave interference mapped to a spectral hue sweep. Cursor = lens warp. Click = new source.",
  },
  {
    id: "photon-burst",
    label: "Photon Burst",
    schema: photonBurstSchema,
    defaults: photonBurstDefaults as unknown as AnyParams,
    Component: PhotonBurst,
    description: "Glowing photons in cosmic noise. Cursor = gravity. Click = rainbow burst.",
  },
  {
    id: "fibonacci-vortex",
    label: "Fibonacci Vortex",
    schema: fibonacciVortexSchema,
    defaults: fibonacciVortexDefaults as unknown as AnyParams,
    Component: FibonacciVortex,
    description: "Golden spiral arms r = k·φ^(θ/½π). Cursor bends paths; click adds bloom.",
  },
  {
    id: "hex-ripple",
    label: "Hex Ripple",
    schema: hexRippleSchema,
    defaults: hexRippleDefaults as unknown as AnyParams,
    Component: HexRipple,
    description: "Hex grid wave interference. Hover highlights cells; click plants sources.",
  },

  {
    id: "recursive-tunnel",
    label: "Recursive Tunnel",
    schema: recursiveTunnelSchema,
    defaults: recursiveTunnelDefaults as unknown as AnyParams,
    Component: RecursiveTunnel,
    description: "Nested polygon zoom tunnel. Mouse = vanishing point; click reverses twist.",
  },
];

/** Initial paramMap — one entry per background, seeded from its defaults. */
export function buildInitialParamMap(): Record<string, AnyParams> {
  return Object.fromEntries(BACKGROUNDS.map((b) => [b.id, { ...b.defaults }]));
}
