import type { CSSProperties } from "react";
import {
  FlowCurrents,
  WaveEther,
  //GravityStorm,
  GeoPulse,
  //VortexBloom,
  //CrystallineDrift,
  AmbientMesh,
  //EmberCascade,
  //CliffordAttractor,
  HarmonicLattice,
  LissajousWeave,
  PhyllotaxisDream,
  //Spirograph,
  //DifferentialGrowth,
  //DoublePendulum,
  FractalNoiseTerrain,
  MoireLattice,
  NeuralWeave,
  OrbitalResonance,
  //ReactionDiffusion,
  RecursiveSubdivision,
  TideHarmonics,
  VoronoiMosaic,
  PlasmaField,
  NebulaVeil,
  PrismaticWave,
  PhotonBurst,
  flowCurrentsSchema,
  flowCurrentsDefaults,
  //gravityStormSchema,
  //gravityStormDefaults,
  geoPulseSchema,
  geoPulseDefaults,
  waveEtherSchema,
  waveEtherDefaults,
  //vortexBloomSchema,
  //vortexBloomDefaults,
  //crystallineDriftSchema,
  //crystallineDriftDefaults,
  ambientMeshSchema,
  ambientMeshDefaults,
  //emberCascadeSchema,
  //emberCascadeDefaults,
  //cliffordAttractorSchema,
  //cliffordAttractorDefaults,
  harmonicLatticeSchema,
  harmonicLatticeDefaults,
  lissajousWeaveSchema,
  lissajousWeaveDefaults,
  phyllotaxisDreamSchema,
  phyllotaxisDreamDefaults,
  //spirographSchema,
  //spirographDefaults,
  //differentialGrowthSchema,
  //differentialGrowthDefaults,
  //doublePendulumSchema,
  //doublePendulumDefaults,
  fractalNoiseTerrainSchema,
  fractalNoiseTerrainDefaults,
  moireLatticeSchema,
  moireLatticeDefaults,
  neuralWeaveSchema,
  neuralWeaveDefaults,
  orbitalResonanceSchema,
  orbitalResonanceDefaults,
  //reactionDiffusionSchema,
  //reactionDiffusionDefaults,
  recursiveSubdivisionSchema,
  recursiveSubdivisionDefaults,
  tideHarmonicsSchema,
  tideHarmonicsDefaults,
  voronoiMosaicSchema,
  voronoiMosaicDefaults,
  plasmaFieldSchema,
  plasmaFieldDefaults,
  nebulaVeilSchema,
  nebulaVeilDefaults,
  prismaticWaveSchema,
  prismaticWaveDefaults,
  photonBurstSchema,
  photonBurstDefaults,
  fibonacciVortexSchema,
  fibonacciVortexDefaults,
  hexRippleSchema,
  hexRippleDefaults,
  recursiveTunnelSchema,
  recursiveTunnelDefaults,
  FibonacciVortex,
  HexRipple,
  RecursiveTunnel,
  type ParamSchema,
} from "@dano796/react-reart";

type BgComponentProps = { style?: CSSProperties; [key: string]: unknown };

export interface DocEntry {
  id: string;
  name: string;
  tag: string;
  desc: string;
  Component: React.ComponentType<BgComponentProps>;
  schema: ParamSchema[];
  defaults: Record<string, unknown>;
  galleryProps: Record<string, unknown>;
}

export const DOC_REGISTRY: DocEntry[] = [
  {
    id: "flow-currents",
    name: "Flow Currents",
    tag: "Perlin Noise · Particles",
    desc: "Thousands of particles trace Perlin noise vector fields, forming organic density maps that slowly evolve over time.",
    Component: FlowCurrents as React.ComponentType<BgComponentProps>,
    schema: flowCurrentsSchema,
    defaults: flowCurrentsDefaults as Record<string, unknown>,
    galleryProps: {
      count: 1600,
      speed: 0.8,
      trailOpacity: 6,
      colorWarm: "#d97757",
      colorCool: "#6a9bcc",
      colorAccent: "#788c5d",
    },
  },
  {
    id: "wave-ether",
    name: "Wave Ether",
    tag: "Interference Waves · Grid",
    desc: "Multi-source sine wave interference patterns ripple across a pixel grid, shifting between crest and trough colors.",
    Component: WaveEther as React.ComponentType<BgComponentProps>,
    schema: waveEtherSchema,
    defaults: waveEtherDefaults as Record<string, unknown>,
    galleryProps: {
      sources: 3,
      frequency: 0.018,
      waveSpeed: 0.025,
      colorCrest: "#00d4ff",
      colorTrough: "#0a0a2e",
      colorMid: "#7b2fff",
    },
  },
  /*{
    id: "gravity-storm",
    name: "Gravity Storm",
    tag: "N-Body · Attractors",
    desc: "Particles orbit moving gravitational attractors, trails painting a choreography of orbital dynamics on the canvas.",
    Component: GravityStorm as React.ComponentType<BgComponentProps>,
    schema: gravityStormSchema,
    defaults: gravityStormDefaults as Record<string, unknown>,
    galleryProps: {
      count: 900,
      attractors: 3,
      gravity: 1.0,
      turbulence: 0.5,
      colorCore: "#ff6b35",
      colorTrail: "#7b5ea7",
    },
  },*/
  {
    id: "geo-pulse",
    name: "Geo Pulse",
    tag: "Geometry · Rotation",
    desc: "Nested rotating polygons at prime-ratio angular velocities, pulsing in scale and connecting vertices across layers.",
    Component: GeoPulse as React.ComponentType<BgComponentProps>,
    schema: geoPulseSchema,
    defaults: geoPulseDefaults as Record<string, unknown>,
    galleryProps: {
      layers: 7,
      sides: 6,
      rotSpeed: 0.008,
      pulse: 0.12,
      connect: 0.4,
      colorPrimary: "#d97757",
      colorSecondary: "#6a9bcc",
      colorAccent: "#e8d87a",
    },
  },
  /*{
    id: "vortex-bloom",
    name: "Vortex Bloom",
    tag: "Vortex · Orbital",
    desc: "Particles spiral under competing vortex attractors, accumulating into mandala-like formations through orbital crystallization.",
    Component: VortexBloom as React.ComponentType<BgComponentProps>,
    schema: vortexBloomSchema,
    defaults: vortexBloomDefaults as Record<string, unknown>,
    galleryProps: {
      vortexCount: 4,
      particleCount: 2000,
      orbitStrength: 1.2,
      spiralTightness: 0.9,
      fadeRate: 4,
      trailWeight: 0.7,
      colorA: "#d97757",
      colorB: "#6a9bcc",
      colorC: "#e8c46a",
    },
  },*/
  /*{
    id: "crystalline-drift",
    name: "Crystalline Drift",
    tag: "Fractal · Symmetry",
    desc: "Recursive branching arms grow from the center, guided by noise, forming snowflake-like crystal mandala structures.",
    Component: CrystallineDrift as React.ComponentType<BgComponentProps>,
    schema: crystallineDriftSchema,
    defaults: crystallineDriftDefaults as Record<string, unknown>,
    galleryProps: {
      symmetry: 6,
      maxDepth: 7,
      angleVariance: 0.5,
      segmentLength: 6,
      branchInterval: 12,
      crystalColor: "#6ab8e8",
      glowColor: "#c4e8ff",
    },
  },*/
  {
    id: "ambient-mesh",
    name: "Ambient Mesh",
    tag: "Network · Subtle",
    desc: "Nodes drift through noise fields, forming dynamic connections — a living network designed as a subtle, aesthetic background.",
    Component: AmbientMesh as React.ComponentType<BgComponentProps>,
    schema: ambientMeshSchema,
    defaults: ambientMeshDefaults as Record<string, unknown>,
    galleryProps: {
      nodeCount: 80,
      connectionDistance: 150,
      motionSpeed: 0.3,
      breatheSpeed: 0.5,
      edgeOpacity: 0.75,
      nodeSize: 4,
      nodeGlow: 0.8,
      nodeColor: "#50b8e8",
      edgeColor: "#50b8e8",
    },
  },
  /*{
    id: "ember-cascade",
    name: "Ember Cascade",
    tag: "Particles · Fire",
    desc: "Thermal particles rise with turbulent motion, glowing through temperature-based color gradients like embers ascending.",
    Component: EmberCascade as React.ComponentType<BgComponentProps>,
    schema: emberCascadeSchema,
    defaults: emberCascadeDefaults as unknown as Record<string, unknown>,
    galleryProps: {
      particleCount: 800,
      sourceCount: 3,
      riseSpeed: 1.2,
      turbulence: 1.0,
      hotColor: "#ffaa33",
      midColor: "#ff5533",
      coolColor: "#aa2233",
    },
  },*/
  /*{
    id: "clifford-attractor",
    name: "Clifford Attractor",
    tag: "Chaos · Fractal",
    desc: "Strange attractor density map revealing the fractal structure of chaotic orbital dynamics through accumulated points.",
    Component: CliffordAttractor as React.ComponentType<BgComponentProps>,
    schema: cliffordAttractorSchema,
    defaults: cliffordAttractorDefaults as unknown as Record<string, unknown>,
    galleryProps: {
      pA: -1.4,
      pB: 1.6,
      pC: 1.0,
      pD: 0.7,
      pointsPerFrame: 8000,
      colorA: "#1a1a2e",
      colorB: "#00d4ff",
    },
  },*/
  {
    id: "harmonic-lattice",
    name: "Harmonic Lattice",
    tag: "Waves · Interference",
    desc: "Two-dimensional standing wave interference patterns with temporal evolution and nodal lines creating harmonic grids.",
    Component: HarmonicLattice as React.ComponentType<BgComponentProps>,
    schema: harmonicLatticeSchema,
    defaults: harmonicLatticeDefaults as unknown as Record<string, unknown>,
    galleryProps: {
      modeCount: 6,
      baseFrequency: 1.0,
      resolution: 80,
      colorA: "#ff6b35",
      colorB: "#f7931e",
      colorC: "#fdc830",
    },
  },
  {
    id: "lissajous-weave",
    name: "Lissajous Weave",
    tag: "Parametric · Harmonic",
    desc: "Multiple Lissajous curves with different frequency ratios morphing through shared phase offset creating woven patterns.",
    Component: LissajousWeave as React.ComponentType<BgComponentProps>,
    schema: lissajousWeaveSchema,
    defaults: lissajousWeaveDefaults as unknown as Record<string, unknown>,
    galleryProps: {
      curveCount: 12,
      freqMax: 5,
      radius: 180,
      phaseSpeed: 1.0,
      colorA: "#ff6b35",
      colorB: "#f7931e",
      colorC: "#fdc830",
    },
  },
  {
    id: "phyllotaxis-dream",
    name: "Phyllotaxis Dream",
    tag: "Spiral · Golden Ratio",
    desc: "Golden angle spiral growth pattern inspired by sunflower seed arrangements and natural phyllotaxis in botanical forms.",
    Component: PhyllotaxisDream as React.ComponentType<BgComponentProps>,
    schema: phyllotaxisDreamSchema,
    defaults: phyllotaxisDreamDefaults as unknown as Record<string, unknown>,
    galleryProps: {
      numPoints: 800,
      spread: 4.5,
      angleScale: 1.0,
      morph: 1.0,
      colorA: "#ff6b35",
      colorB: "#f7931e",
      colorC: "#fdc830",
    },
  },
  /*{
    id: "spirograph",
    name: "Spirograph",
    tag: "Geometric · Curves",
    desc: "Hypotrochoid curves traced by rolling circles, creating intricate geometric rosettes and patterns with mathematical precision.",
    Component: Spirograph as React.ComponentType<BgComponentProps>,
    schema: spirographSchema,
    defaults: spirographDefaults as unknown as Record<string, unknown>,
    galleryProps: {
      R: 120,
      r: 45,
      d: 70,
      speed: 1.0,
      lineWeight: 1.2,
      colorA: "#ff6b35",
      colorB: "#f7931e",
      colorC: "#fdc830",
    },
  },*/
  /*{
    id: "differential-growth",
    name: "Differential Growth",
    tag: "Organic · Simulation",
    desc: "Organic growth simulation with spring forces, repulsion, and noise-guided expansion creating folded biological forms.",
    Component: DifferentialGrowth as React.ComponentType<BgComponentProps>,
    schema: differentialGrowthSchema,
    defaults: differentialGrowthDefaults as unknown as Record<string, unknown>,
    galleryProps: {
      growthRate: 0.8,
      repelRadius: 12,
      stepsPerFrame: 3,
      fadeRate: 18,
      colorA: "#50b8e8",
      colorB: "#e850b8",
    },
  },*/
  /*{
    id: "double-pendulum",
    name: "Double Pendulum",
    tag: "Chaos · Physics",
    desc: "Chaotic dynamics visualization using RK4 integration showing diverging trajectories from similar initial conditions.",
    Component: DoublePendulum as React.ComponentType<BgComponentProps>,
    schema: doublePendulumSchema,
    defaults: doublePendulumDefaults as unknown as Record<string, unknown>,
    galleryProps: {
      seed: 4242,
      numPendulums: 21,
      length1: 140,
      length2: 140,
      gravity: 0.9,
      simSpeed: 2.5,
      fadeRate: 1,
      bgColor: "#0d1117",
      colorA: "#ff6b9d",
      colorB: "#4ecdc4",
      colorC: "#ffe66d",
    },
  },¨*/
  {
    id: "fractal-noise-terrain",
    name: "Fractal Noise Terrain",
    tag: "Fractal · Landscape",
    desc: "Layered octaves of Perlin noise creating procedural landscapes with elevation-based coloring and lighting effects.",
    Component: FractalNoiseTerrain as React.ComponentType<BgComponentProps>,
    schema: fractalNoiseTerrainSchema,
    defaults: fractalNoiseTerrainDefaults as unknown as Record<string, unknown>,
    galleryProps: {
      octaves: 6,
      persistence: 0.5,
      scale: 4.0,
      lighting: 2.5,
      resolution: 120,
      colorA: "#1a2332",
      colorB: "#2d4a5a",
      colorC: "#5a7a6a",
      colorD: "#d4e8e0",
    },
  },
  {
    id: "moire-lattice",
    name: "Moire Lattice",
    tag: "Geometric · Interference",
    desc: "Rotating line grids creating interference patterns and moiré effects through overlapping parallel lines at different angles.",
    Component: MoireLattice as React.ComponentType<BgComponentProps>,
    schema: moireLatticeSchema,
    defaults: moireLatticeDefaults as unknown as Record<string, unknown>,
    galleryProps: {
      gridCount: 5,
      lineSpacing: 18,
      rotSpeed: 1.0,
      colorA: "#50b8e8",
      colorB: "#e8b850",
      colorC: "#e850b8",
    },
  },
  {
    id: "neural-weave",
    name: "Neural Weave",
    tag: "Network · Neural",
    desc: "Network of nodes with traveling signal pulses creating dynamic neural-like activation patterns across connections.",
    Component: NeuralWeave as React.ComponentType<BgComponentProps>,
    schema: neuralWeaveSchema,
    defaults: neuralWeaveDefaults as unknown as Record<string, unknown>,
    galleryProps: {
      nodeCount: 45,
      connectionRadius: 180,
      signalCount: 8,
      signalSpeed: 1.2,
      nodeColor: "#50b8e8",
      edgeColor: "#50b8e8",
      signalColor: "#e8b850",
    },
  },
  {
    id: "orbital-resonance",
    name: "Orbital Resonance",
    tag: "Orbital · Harmonic",
    desc: "Bodies orbit at resonant period ratios creating harmonic patterns and Lissajous-like trajectories in orbital space.",
    Component: OrbitalResonance as React.ComponentType<BgComponentProps>,
    schema: orbitalResonanceSchema,
    defaults: orbitalResonanceDefaults as unknown as Record<string, unknown>,
    galleryProps: {
      bodyCount: 5,
      simSpeed: 1.0,
      trailLength: 200,
      fadeTrails: true,
      colorA: "#ff6b35",
      colorB: "#f7931e",
      colorC: "#fdc830",
      colorD: "#50b8e8",
    },
  },
  /*{
    id: "reaction-diffusion",
    name: "Reaction Diffusion",
    tag: "Simulation · Organic",
    desc: "Gray-Scott model creating organic pattern formation through chemical reaction simulation with diffusion dynamics.",
    Component: ReactionDiffusion as React.ComponentType<BgComponentProps>,
    schema: reactionDiffusionSchema,
    defaults: reactionDiffusionDefaults as unknown as Record<string, unknown>,
    galleryProps: {
      Da: 1.0,
      Db: 0.5,
      f: 0.055,
      k: 0.062,
      stepsPerFrame: 10,
      colorA: "#1a1a2e",
      colorB: "#00d4ff",
    },
  },*/
  {
    id: "recursive-subdivision",
    name: "Recursive Subdivision",
    tag: "Geometric · Mondrian",
    desc: "Binary space partitioning creating Mondrian-like compositions with golden ratio splits and depth-based coloring.",
    Component: RecursiveSubdivision as React.ComponentType<BgComponentProps>,
    schema: recursiveSubdivisionSchema,
    defaults: recursiveSubdivisionDefaults as unknown as Record<
      string,
      unknown
    >,
    galleryProps: {
      maxDepth: 6,
      splitProbability: 0.85,
      animated: true,
      animSpeed: 1.5,
      colorA: "#50b8e8",
      colorB: "#e8b850",
      colorC: "#e850b8",
    },
  },
  {
    id: "tide-harmonics",
    name: "Tide Harmonics",
    tag: "Waves · Ocean",
    desc: "Multiple wave sources creating interference patterns along horizontal lines like ocean tides with harmonic motion.",
    Component: TideHarmonics as React.ComponentType<BgComponentProps>,
    schema: tideHarmonicsSchema,
    defaults: tideHarmonicsDefaults as unknown as Record<string, unknown>,
    galleryProps: {
      waveCount: 5,
      gridRows: 35,
      frequency: 1.0,
      amplitude: 45,
      colorA: "#50b8e8",
      colorB: "#e850b8",
    },
  },
  {
    id: "voronoi-mosaic",
    name: "Voronoi Mosaic",
    tag: "Tessellation · Geometric",
    desc: "Moving seed points creating dynamic Voronoi tessellation with edge-enhanced cells forming organic mosaic patterns.",
    Component: VoronoiMosaic as React.ComponentType<BgComponentProps>,
    schema: voronoiMosaicSchema,
    defaults: voronoiMosaicDefaults as unknown as Record<string, unknown>,
    galleryProps: {
      seedCount: 25,
      moveSpeed: 0.5,
      edgeContrast: 1.2,
    },
  },
  {
    id: "plasma-field",
    name: "Plasma Field",
    tag: "Shader · Noise",
    desc: "Domain-warped fractional Brownian motion rendered at true pixel resolution via a WebGL2 fragment shader. Three color stops shift through the warped noise field.",
    Component: PlasmaField as React.ComponentType<BgComponentProps>,
    schema: plasmaFieldSchema,
    defaults: plasmaFieldDefaults as unknown as Record<string, unknown>,
    galleryProps: {
      speed: 1.0,
      scale: 2.5,
      contrast: 2.2,
      colorA: "#0d1b6e",
      colorB: "#c0146c",
      colorC: "#f5a623",
    },
  },
  {
    id: "nebula-veil",
    name: "Nebula Veil",
    tag: "Shader · Volumetric",
    desc: "Three superimposed simplex noise planes interfere at different frequencies to create a volumetric nebula curtain with radial depth and luminous cloud structures.",
    Component: NebulaVeil as React.ComponentType<BgComponentProps>,
    schema: nebulaVeilSchema,
    defaults: nebulaVeilDefaults as unknown as Record<string, unknown>,
    galleryProps: {
      amplitude: 2.0,
      density: 2.2,
      blend: 0.6,
      colorA: "#0a0a2e",
      colorB: "#7b2fbe",
      colorC: "#00d4ff",
    },
  },
  {
    id: "prismatic-wave",
    name: "Prismatic Wave",
    tag: "Waves · Prism",
    desc: "Wave interference mapped to a full spectral hue sweep — like white light through a prism. Move the cursor to bend the chromatic bands; click to plant new wave sources.",
    Component: PrismaticWave as React.ComponentType<BgComponentProps>,
    schema: prismaticWaveSchema,
    defaults: prismaticWaveDefaults as unknown as Record<string, unknown>,
    galleryProps: {
      sources: 5,
      frequency: 0.012,
      dispersion: 300,
      hueOffset: 0,
      saturation: 0.9,
      brightness: 0.65,
      lensStrength: 1.0,
    },
  },
  {
    id: "photon-burst",
    name: "Photon Burst",
    tag: "Particles · Glow",
    desc: "Glowing photons drift through cosmic noise currents. Move the cursor to bend paths with gravitational pull; click anywhere to detonate a radial rainbow burst.",
    Component: PhotonBurst as React.ComponentType<BgComponentProps>,
    schema: photonBurstSchema,
    defaults: photonBurstDefaults as unknown as Record<string, unknown>,
    galleryProps: {
      count: 800,
      speed: 1.0,
      trailOpacity: 12,
      burstSize: 28,
      cursorGravity: 0.18,
    },
  },
  {
    id: "fibonacci-vortex",
    name: "Fibonacci Vortex",
    tag: "Fibonacci · Spiral",
    desc: "Particles travel along golden spiral arms radiating from bloom centers. Move the cursor to gravitationally bend nearby paths; click to plant a new spiral origin.",
    Component: FibonacciVortex as React.ComponentType<BgComponentProps>,
    schema: fibonacciVortexSchema,
    defaults: fibonacciVortexDefaults as unknown as Record<string, unknown>,
    galleryProps: {
      numArms: 8,
      particlesPerArm: 90,
      speed: 1.0,
      trailOpacity: 20,
      colorPrimary: "#f5c842",
      colorSecondary: "#e05a20",
      colorAccent: "#8c42f5",
    },
  },
  {
    id: "hex-ripple",
    name: "Hex Ripple",
    tag: "Hexagonal · Grid",
    desc: "A hexagonal tessellation with multi-source wave superposition. Chromatic interference patterns ripple across the grid. Hover highlights cells; click anywhere to plant a new wave source.",
    Component: HexRipple as React.ComponentType<BgComponentProps>,
    schema: hexRippleSchema,
    defaults: hexRippleDefaults as unknown as Record<string, unknown>,
    galleryProps: {
      cellSize: 22,
      waveSpeed: 1.0,
      frequency: 0.038,
      colorTrough: "#080820",
      colorMid: "#1a6fff",
      colorCrest: "#00ffcc",
    },
  },

  {
    id: "recursive-tunnel",
    name: "Recursive Tunnel",
    tag: "Recursive · Geometric",
    desc: "Concentric nested polygons zoom inward with cumulative twist — a hypnotic recursive depth tunnel. Move the cursor to shift the vanishing point; click to reverse the twist direction.",
    Component: RecursiveTunnel as React.ComponentType<BgComponentProps>,
    schema: recursiveTunnelSchema,
    defaults: recursiveTunnelDefaults as unknown as Record<string, unknown>,
    galleryProps: {
      sides: 6,
      layers: 22,
      zoomSpeed: 0.1,
      twistPerLayer: 0.11,
      parallaxStrength: 0.28,
      colorInner: "#ff2d78",
      colorMid: "#2d78ff",
      colorOuter: "#2dffbe",
    },
  },
];
